package configPac;

import java.util.Scanner;

public class Config {

	public static Scanner scan = new Scanner(System.in); 
	public static int mapRow=0;  
	public static int mapCol=0;  
	final public static String UP = "W";  
	final public static String DOWN = "S";
	final public static String LEFT = "A";  
	final public static String RIGHT = "D";
	final public static String QUIT = "Q";
	final public static String GET = "GET";
	final public static String sGET = "G";
	final public static String EAT = "EAT";
	final public static String sEAT = "E";
	final public static String PUSH = "PUSH";
	final public static String sPUSH = "P";
	final public static String JUMP = "JUMP";
	final public static String sJUMP = "J";
	final public static String OPEN = "OPEN";
	final public static String sOPEN = "O";
	final public static String ATTACK = "ATTACK";
	final public static String sATTACK = "A";
	final public static String NOTHING = "NOTHING";
	final public static String sNOTHING = "N";
	final public static String LEAVE = "LEAVE";
	final public static String sLEAVE = "L";
	final public static String mainMenu = "(A)Left (D)Right (W)Up (S)Down (Q)uit: "; 
	final public static String foodMenu = "(E)at (N)othing: "; 
	final public static String foodEat = "You ate the food."; 
	final public static String boxMenu = "(O)pen (N)othing: "; 
	final public static String boxOpen = "You opened the box."; 
	final public static String keyMenu = "(G)et (N)othing: "; 
	final public static String keyGet = "You got the key."; 
	final public static String doorMenu = "(O)pen (N)othing: "; 
	final public static String doorOpen = "You opened the door."; 
	final public static String doorCantOpen = "You can't open the door."; 
	final public static String boxToFood = "A food was in the box."; 
	final public static String boxToWeapon = "An weapon was in the box."; 
	final public static String turnOnLight = "A button was in the box. You turned on the light."; 
	final public static String turnOffLight = "A button was in the box. You turned off the light."; 
	final public static String rockMenu = "(P)ush (N)othing: "; 
	final public static String rockPush = "Rock moved!"; 
	final public static String teleportMenu = "(J)ump (N)othing: "; 
	final public static String teleportJump = "You jumped into other teleport"; 
	final public static String weaponMenu = "(G)et (N)othing: "; 
	final public static String weaponGet = "Short sword equipped!"; 
	final public static String monsterMenu = "(A)ttack (L)eave: "; 
	final public static String monsterKill = "Victory!"; 
	final public static String sMonsterKill = "You got Exp!"; 
	final public static String monsterAttack = "The monster attacked you!!!"; 
	final public static String playerAttack = "you attacked the monster!!!"; 
	final public static String playerLeave = "You fleed from the monster."; 
	final public static String playerDie = "You died."; 
	final public static String monster = "Monster's HP: "; 
	final public static String playerHP = "Player  HP: "; 
	final public static String playerLv = "LV: "; 
	final public static String playerExp = "\tExp: "; 
	final public static String playerLvUP = "Level up!"; 
	final public static String damage = "\t Damage: "; 
	final public static String shortSword = "\tShort Sword"; 
	final public static String bareHands = "\t\t Bare hands"; 
	final public static String inputError = "Enter the right word"; 
	final public static String x = "\tX: "; 
	final public static String y = " Y: "; 
	final public static String MAP_FILENAME = "c:/oop/map.dat";
}
